<section>
    <h2><?=$title?></h2>
    <?php if(count($error)>0) :?>
        <?php foreach($error as $err):?>
            <p><?=$err?></p>
        <?php endforeach;?>
    <?php endif;?>
    <form method="get" action="categories.php">
        <p>
            <label for="nomCategorie">Nouvelle catégorie</label>
            <input type="text" name="nomCategorie" id="nomCategorie" placeholder="Nom de la catégorie" value=""/>
        </p>
        <input type="submit" value="Envoyer" />
    </form>

    <table>
        <thead>
            <th>Id</th>          
            <th>Catégories d'articles</th>
            <th>Modifier</th>          
            <th>Supprimer</th>
        </thead>
        <tbody>
            <?php foreach($cats as $cat):?>
                <tr>
                    <td><?=$cat['cat_id']?></td>
                    <td><?=$cat['cat_name']?></td>
                    <td><input type="submit" value="Modifier"></td>
                    <td><input type="submit" value="Supprimer"></td>
                </tr>  
            <?php endforeach;?> 
        </tbody>
    </table>

</section>