<!DOCTYPE html>
<html lang="fr">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title><?=$title?></title>

  </head>

  <body>
    <header>
        <h1>Chezpas Blog</h1>
          <nav>
            <a href="#">Accueil</a>
            <a href="#">ChezPas</a>
            <a href="#">Nous contacter</a>
          </nav>
          <input type="submit" value="Deconnexion" />
    </header>
    <main>
      <?php include('tpl/'.$vue);?>
    </main>

  </body>

</html>
