<!DOCTYPE html>
<html lang="fr">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title><?=$title?></title>

  </head>

  <body>
    <header>
        <h1>Chezpas Blog</h1>

          <nav>
            <a href="addUser.php">Ajouter un utilisateur</a>
            <a href="listUsers.php">Liste des utilisateurs</a>
            <a href="addArticle.php">Ajouter un article</a>
          </nav>

          <form method="post" action="logout.php">
            <input type="submit" value="Déconnexion" />
          </form>
          
          <?php if(isset($_SESSION['connect']) && $_SESSION['connect'] == true):?>
            <p>Bonjour,<?=$_SESSION['user'][2]?> <?=$_SESSION['user'][1]?></p>
          <?php else:?>
            <p>Veuillez vous connecter</p>
          <?php endif;?>
    </header>

    <main>
      <?php include('tpl/'.$vue);?>
    </main>

  </body>

</html>
