<section>
    <h2><?=$title?></h2>

        <table>
            <thead>
                <th>Identifiant</th>
                <th>Nom</th>
                <th>Prénom</th>
                <th>Pseudo</th>
                <th>Email</th>
                <th>Mot de passe</th>
                <th>Biographie</th>
                <th>Modifier</th>
                <th>Supprimer</th>
            </thead>
            <tbody>
                <?php foreach($users as $user):?>
                    <tr>
                        <td><?=$user['user_id']?></td>
                        <td><?=$user['user_nom']?></td>
                        <td><?=$user['user_prenom']?></td>
                        <td><?=$user['user_username']?></td>
                        <td><?=$user['user_email']?></td>
                        <td><?=$user['user_password']?></td>
                        <td><?=$user['user_bio']?></td>
                        <td><input type="submit" value="Modifier"></td>   
                        <form method="post" action="delUsers.php">                    
                        <td><input type="submit" value="Supprimer"></td>  
                        </form> 
                    </tr>  
                <?php endforeach;?> 
            </tbody>
        </table>

</section>