<section>
    <h2><?=$title?></h2>
    <?php if($impossible != false) :?>    
        <p><?=$impossible?></p>
    <?php endif;?>
    <form method="post" action="login.php">
        <p>
            <label for="mail">Email :</label>
            <input type="email" name="mail" id="mail" placeholder="Votre Email" value=""/>
        </p>        
        <p>
            <label for="pass">Mot de passe :</label>
            <input type="password" name="pass" id="pass" placeholder="Votre mot de passe" value=""/>
        </p>
        <input type="submit" value="Envoyer" />
    </form>
</section